version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      # minio で設定しているクレデンシャル情報と同じ値
      AWS_ACCESS_KEY_ID: minio
      AWS_SECRET_ACCESS_KEY: minio123
    command: go run main.go
    tty: true
    volumes:
      - ".:/app"
    ports:
      # 他のアプリケーションと衝突しないように適当なポートを設定
      - "5000:80"
    depends_on:
      - "elasticmq"
      - "minio"
    networks:
      - net1
  minio:
    image: minio/minio
    environment:
      # クレデンシャル情報
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    entrypoint: sh
    command: -c "mkdir -p /data/.minio.sys/buckets && cp -r /export/* /data/ && minio server /data --console-address :9005"
    volumes:
      - s3-data:/data
      - ./minio/export:/export
    ports:
      # 他のアプリケーションと衝突しないように適当なポートを設定
      - "9090:9000"
      - "9005:9005"
    networks:
      - net1
  elasticmq:
    image: softwaremill/elasticmq
    volumes:
      # ElasticMQの設定ファイル
      - ./elasticmq/conf/custom.conf://opt/elasticmq.conf:ro
    ports:
      - "9324:9324"
      - "9325:9325"
    networks:
      - net1
volumes:
  s3-data:
networks:
  net1: